package com.docpilot.backend.ai.context;

public enum RouteDecision {
    MODEL_ONLY,
    AUTO_NO_KB_MODEL,
    AUTO_INTENT_NOT_TRIGGERED_MODEL,
    AUTO_RAG_EVIDENCE,
    AUTO_NO_EVIDENCE_MODEL,
    AUTO_REQUIRED_NO_EVIDENCE_FALLBACK,
    STRICT_NO_KB_FALLBACK,
    STRICT_KB_EVIDENCE,
    STRICT_NO_EVIDENCE_FALLBACK,
    LEGACY_UNKNOWN
}
