CREATE TABLE IF NOT EXISTS tb_conversation (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'Owner user id',
    title VARCHAR(128) DEFAULT NULL COMMENT 'Conversation title',
    context_mode VARCHAR(32) NOT NULL DEFAULT 'RECENT_TURNS' COMMENT 'Context mode: RECENT_TURNS, AGENT_MEMORY',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT 'Status: ACTIVE, DELETED',
    bound_knowledge_base_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'Bound knowledge base id',
    summary_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether summary is enabled',
    memory_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether memory is enabled',
    last_message_time DATETIME DEFAULT NULL COMMENT 'Last message time',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
    PRIMARY KEY (id),
    KEY idx_conversation_user_id (user_id),
    KEY idx_conversation_user_status (user_id, status),
    KEY idx_conversation_last_message_time (last_message_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Conversation context table';

CREATE TABLE IF NOT EXISTS tb_conversation_message (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    conversation_id BIGINT UNSIGNED NOT NULL COMMENT 'Conversation id',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'Owner user id',
    role VARCHAR(32) NOT NULL COMMENT 'Message role: USER, ASSISTANT, SYSTEM, TOOL',
    content LONGTEXT NOT NULL COMMENT 'Message content',
    sequence_no INT NOT NULL COMMENT 'Sequence number within conversation',
    token_count INT NOT NULL DEFAULT 0 COMMENT 'Estimated token count',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT 'Status: ACTIVE, DELETED',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    PRIMARY KEY (id),
    UNIQUE KEY uk_conversation_sequence (conversation_id, sequence_no),
    KEY idx_message_conversation_seq (conversation_id, sequence_no),
    KEY idx_message_user_conversation (user_id, conversation_id),
    KEY idx_message_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Conversation message table';

CREATE TABLE IF NOT EXISTS tb_conversation_summary (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    conversation_id BIGINT UNSIGNED NOT NULL COMMENT 'Conversation id',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'Owner user id',
    summary TEXT NOT NULL COMMENT 'Conversation summary',
    covered_start_seq INT DEFAULT NULL COMMENT 'Covered start sequence',
    covered_end_seq INT DEFAULT NULL COMMENT 'Covered end sequence',
    summary_version INT NOT NULL DEFAULT 1 COMMENT 'Summary strategy version',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT 'Status: ACTIVE, STALE, GENERATING, FAILED, DELETED',
    token_count INT NOT NULL DEFAULT 0 COMMENT 'Estimated token count',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
    PRIMARY KEY (id),
    KEY idx_summary_conversation (conversation_id),
    KEY idx_summary_user_conversation (user_id, conversation_id),
    KEY idx_summary_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Conversation rolling summary table';

CREATE TABLE IF NOT EXISTS tb_context_trace (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    conversation_id BIGINT UNSIGNED NOT NULL COMMENT 'Conversation id',
    message_id BIGINT UNSIGNED NOT NULL COMMENT 'Assistant message id',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'Owner user id',
    context_mode VARCHAR(32) NOT NULL COMMENT 'Context mode',
    grounding_policy VARCHAR(32) DEFAULT NULL COMMENT 'Grounding policy for this answer',
    route_decision VARCHAR(64) DEFAULT NULL COMMENT 'Resolved answer route',
    llm_called TINYINT(1) DEFAULT NULL COMMENT 'Whether model provider was called',
    summary_used TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether summary was used',
    recent_turn_count INT NOT NULL DEFAULT 0 COMMENT 'Recent turn count',
    recent_message_count INT NOT NULL DEFAULT 0 COMMENT 'Recent message count',
    memory_used TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether memory was used',
    memory_count INT NOT NULL DEFAULT 0 COMMENT 'Memory item count',
    memory_types_json TEXT COMMENT 'Memory type list as JSON',
    rag_triggered TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether knowledge-base RAG was triggered',
    rag_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether knowledge-base evidence was required',
    knowledge_base_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'Bound knowledge base id',
    evidence_count INT NOT NULL DEFAULT 0 COMMENT 'Knowledge-base evidence item count',
    no_evidence TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether retrieval had no evidence',
    document_hit_counts_json TEXT COMMENT 'Document hit counts as JSON',
    max_prompt_tokens INT NOT NULL DEFAULT 0 COMMENT 'Prompt token budget',
    estimated_prompt_tokens INT NOT NULL DEFAULT 0 COMMENT 'Estimated prompt tokens',
    truncated TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether optional context was dropped',
    truncated_types_json TEXT COMMENT 'Dropped context type list as JSON',
    fallback_used TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether fallback answer was used',
    fallback_reason VARCHAR(64) DEFAULT NULL COMMENT 'Fallback reason',
    model_call_skipped TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether model call was skipped',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    PRIMARY KEY (id),
    UNIQUE KEY uk_context_trace_message (message_id),
    KEY idx_context_trace_conversation (conversation_id),
    KEY idx_context_trace_user_conversation (user_id, conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Conversation context trace summary table';

CREATE TABLE IF NOT EXISTS tb_user_memory (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    user_id BIGINT UNSIGNED NOT NULL COMMENT 'Owner user id',
    memory_type VARCHAR(32) NOT NULL COMMENT 'Memory type',
    content TEXT NOT NULL COMMENT 'Memory content',
    source_type VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT 'Source type',
    source_conversation_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'Source conversation id',
    source_message_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'Source message id',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT 'Status: SUGGESTED, ACTIVE, IGNORED, ARCHIVED, DELETED',
    priority INT NOT NULL DEFAULT 0 COMMENT 'Higher priority is selected first',
    confidence DECIMAL(5,4) NOT NULL DEFAULT 1.0000 COMMENT 'Confidence score',
    last_used_time DATETIME DEFAULT NULL COMMENT 'Last used time',
    use_count INT NOT NULL DEFAULT 0 COMMENT 'Use count',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
    PRIMARY KEY (id),
    KEY idx_memory_user_status (user_id, status),
    KEY idx_memory_user_type (user_id, memory_type),
    KEY idx_memory_source_conversation (source_conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='User long-term memory table';
